name: autodeploy

on:
  push:
    branches: [master]

jobs:
  publish-gpr:
    name: Publish to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git User
        run: |
          git config --global user.name "The Power Ecosystem"
          git config --global user.email "ext@thepower.io"

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bootstrap lerna
        run: yarn bootstrap

      - name: Bump versions and publish packages
        run: |
          yarn version:ci
          yarn publish:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
